### PR TITLE
Fixes #713 adds target='_blank' for auto links if the option is set

### LINKED ISSUE #713: targetBlank = true not working for automatic links (when autoLink = true)
When links are created automatically and the targetBlank is set to true, the automatically created links will still not have any target set. 

Similar to #508

### PR DESCRIPTION
**Pull request by filipkis**

### CODE REVIEW

File: src/js/extensions/auto-link.js [hunk 1]
```diff
@@ -205,7 +205,7 @@ LINK_REGEXP_TEXT =
 
         createAutoLink: function (textNodes, href) {
             href = Util.ensureUrlHasProtocol(href);
-            var anchor = Util.createLink(this.document, textNodes, href),
+            var anchor = Util.createLink(this.document, textNodes, href, this.getEditorOption('targetBlank')),
```
Comment (j0k3r) [inline src/js/extensions/auto-link.js]: I was wondering why autoLink extension use `Util.createLink` instead of `Core.createLink` ? Because, `Core.createLink` already handle `targetBlank` option ([see](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js#L1054-L1056)).

Any idea @patrick-webs ?

Comment (nmielnik) [inline src/js/extensions/auto-link.js]: The purpose of `Util.createLink` is to build an anchor tag around a set of textnodes, and it will actually extract the text nodes from the DOM, and insert them into the anchor that is returned (presumably to be inserted somewhere by the user).

`Core.createLink` is your generic use case, where you just build an anchor around the user's current selection.

Now that you bring it up, I'm thinking we should rename `Util.createLink` or move it out of `Util` altogether. We can do that in a follow-up to this.

Comment (nmielnik) [inline src/js/extensions/auto-link.js]: Also, it looks like both the auto-link extension and `Core.createLink` call `Util.createLink`, so I guess it shouldn't be moved out of Util...and maybe it does make sense to be called this...have to think on it.

File: src/js/util.js [hunk 2]
```diff
@@ -106,10 +106,13 @@ var Util;
          * descendants of the same closest block container. If the preconditions are not met, unexpected
          * behavior will result.
          */
-        createLink: function (document, textNodes, href) {
+        createLink: function (document, textNodes, href, blank) {
```
Comment (nmielnik) [inline src/js/util.js]: Could you change this argument from `blank` (`boolean`) to `target` (`string`)?  It will be easier to maintain the helper function in the future if you can always pass in the desired target and not just a boolean specifying a specific target.

File: src/js/extensions/auto-link.js (hunk 1 above)
Comment (j0k3r) [inline src/js/extensions/auto-link.js]: Yeah, it shouldn't be removed.
I think it could lead to a confusion since both method _seem_ to the same action and they have the same name

**Comment by j0k3r** [comment]
Everything seems ok :+1:
