### PR TITLE
Fix #751 - issue with finding anchor when clicking anchor button

### LINKED ISSUE #751: Editor refuse to create links if there is already a link positioned in the very beginning.
Hello!

The bug can be reproduced here with latest Chrome : https://yabwe.github.io/medium-editor/
Create a link on "My father" and then try to create another one after. It fails and refuse to create new links.

screen shot 2015-07-29 at 10 42 27

The script think that there is already a link so refuse to create a new one. 
Here is the part of the code that seems to be wrong :

```js
            var selectedParentElement = Selection.getSelectedParentElement(Selection.getSelectionRange(this.document)),
                firstTextNode = Util.getFirstTextNode(selectedParentElement);

            if (Util.getClosestTag(firstTextNode, 'a')) {
                return this.execAction('unlink');
            }
```

### PR DESCRIPTION
**Pull request by nmielnik**
This fixes #751 

When the user clicks the 'anchor' button, we attempt to find an existing anchor within the selection.  If there is one, we 'unlink' that anchor, otherwise we display the anchor form an allow them to create a link.

There was a bug in the code that tries to find the existing link.  It was incorrectly looking for the first text node within the parent selection node, which manifested itself as being unable to create a link when a link appeared as a previousSibling of a text node which was being selected.

### CODE REVIEW

**Comment by nmielnik** [comment]
I believe this also fixes issue #738

File: src/js/extensions/anchor.js [hunk 1]
```diff
@@ -60,10 +60,9 @@ var AnchorForm;
             event.preventDefault();
             event.stopPropagation();
 
-            var selectedParentElement = Selection.getSelectedParentElement(Selection.getSelectionRange(this.document)),
-                firstTextNode = Util.getFirstTextNode(selectedParentElement);
+            var selectedParentElement = Selection.getSelectedParentElement(Selection.getSelectionRange(this.document));
```
Comment (patrick-webs) [inline src/js/extensions/anchor.js]: this should also handle the case where the start container of the selection is the anchor tag.

File: src/js/extensions/anchor.js [hunk 2]
```diff
@@ -60,10 +60,17 @@ var AnchorForm;
...
-                firstTextNode = Util.getFirstTextNode(selectedParentElement);
+            var linkSelected = false,
+                range = Selection.getSelectionRange(this.document);
+
+            if (range.startContainer.nodeName.toLowerCase() === 'a' ||
+                range.endContainer.nodeName.toLowerCase() === 'a') {
+                linkSelected = true;
+            } else if (Util.getClosestTag(Selection.getSelectedParentElement(range), 'a')) {
+                linkSelected = true;
+            }
```
Comment (j0k3r) [inline src/js/extensions/anchor.js]: Why not a single `if` ?

```js
if (range.startContainer.nodeName.toLowerCase() === 'a' ||
    range.endContainer.nodeName.toLowerCase() === 'a' ||
    Util.getClosestTag(Selection.getSelectedParentElement(range), 'a')) {
    return this.execAction('unlink');
}

Comment (nmielnik) [inline src/js/extensions/anchor.js]: I was trying to make things more readable since these are 2 different kinds of checks, but I agree it'll be easier to just make it one if statement

**Comment by j0k3r** [comment]
Maybe you can add an extra comment to explain the "combination" conditions then


--
Jeremy
