### PR TITLE
Fix #757 Track beginning of paragraph in exportSelection

### LINKED ISSUE #757: Buggy restore selection when creating link on first word in paragraph
Steps to reproduce: 

1. Create a new paragraph
2. Select first word in paragraph
3. Create a link
4. this.base.restoreSelection() doesn't restore selection on link correctly (what is visually seen). MediumEditor.selection.getSelectionStart(this.base.options.ownerDocument) returns previous paragraph, not anchor node from current paragraph. It is problematic when you want to apply custom class on link or, in my case, add custom data attributes to link.

mediumeditor___demo

### PR DESCRIPTION
**Pull request by nmielnik**
This fixes an issue when saving selection if the cursor is at beginning of a paragraph, but not preceded by empty paragraphs.

We track whether the cursor is at the beginning of a paragraph that has empty paragraphs before it by counting the empty paragraph and storing in the selection data.  However, if the paragraph did not have empty paragraphs in front of it, we didn't store anything, which made the selection get set to the end of the paragraph before it, rather the beginning of the paragraph it should be within.

The fix is to always track if the cursor is at the beginning of a paragraph, and set `emptyBlocksIndex` to `0` if there are no empty paragraphs before it.  Before, this case would have just left `emptyBlocksIndex` as undefined.

This manifested itself in the re-opened issue for #757 and should now be fixed.

### CODE REVIEW

File: src/js/selection.js [hunk 1]
```diff
@@ -180,23 +180,24 @@ var Selection;
...
+        // If the paragraph/block is preceeded by empty paragraphs/block (with no text)
+        // it will return the number of empty paragraphs before the cursor.
+        // Otherwise, it will return 0, which indicates the cursor is at the beginning
+        // of a paragraph/block, and not at the end of the paragraph/block before it
         getIndexRelativeToAdjacentEmptyBlocks: function (doc, root, cursorContainer, cursorOffset) {
             // If there is text in front of the cursor, that means there isn't only empty blocks before it
-            if (cursorContainer.nodeType === 3 && cursorOffset > 0) {
-                return 0;
+            if (cursorContainer.textContent.length > 0 && cursorOffset > 0) {
+                return -1;
```
Comment (patrick-webs) [inline src/js/selection.js]: this will change the behavior if the cursor was after the IMG in the following case. Whether this is important I don't know, since in either case the old code also would restore the cursor the wrong place, just to a place that is slightly less wrong:

    <p>Hello world</p>
    <p></br></p>
    <p>The quick brown fox</p>

Comment (nmielnik) [inline src/js/selection.js]: So this is not actually a change in behavior, the cursor is restored to the same location as the previous code did.
